on:
  push:
    branches:
      - master
  pull_request:
    types: [ opened, synchronize, reopened ]
jobs:
  build:
    runs-on: docker
    container:
      image: git.myservermanager.com/msm/executor-ubuntu-build-essential:latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout
      - uses: ./.forgejo/actions/tooling
        name: Tooling
      - uses: ./.forgejo/actions/native-build
        name: Native build
      - uses: ./.forgejo/actions/oci-prepare
        name: OCI prepare
      - uses: ./.forgejo/actions/oci-build
        name: OCI build
        with:
          loadImageServer: false
          loadImageStandaloneWebInterface: false
