on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: native
    steps:
      - uses: actions/checkout@v3
        name: Checkout
      - uses: ./.forgejo/actions/native-build
        name: Native - build
      - uses: ./.forgejo/actions/native-scan
        name: Native - scan
      - uses: ./.forgejo/actions/native-test
        name: Native - test
      - uses: ./.forgejo/actions/oci-prepare
        name: OCI - prepare
      - uses: ./.forgejo/actions/oci-build
        name: OCI - build
