on:
  pull_request:
    types: [ opened, synchronize, reopened ]
jobs:
  mr:
    runs-on: docker
    container:
      image: git.myservermanager.com/msm/executor-ubuntu-build-essential:latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.forgejo/actions/prepare
      - uses: ./.forgejo/actions/native-build
      - uses: ./.forgejo/actions/oci-build