on:
  workflow_dispatch:
    inputs:
      version:
        description: "version to use"
        required: true
        type: string
jobs:
  release:
    runs-on: native
    steps:
      - uses: actions/checkout@v3
        name: Checkout
      - uses: ./.forgejo/actions/native-build
        name: Native - build
      - uses: ./.forgejo/actions/native-scan
        name: Native - scan
      - uses: ./.forgejo/actions/native-test
        name: Native - test
      - uses: ./.forgejo/actions/oci-prepare
        name: OCI - prepare
      - uses: ./.forgejo/actions/oci-release
        name: OCI - release
        with:
          version: ${{ inputs.version }}
          registryFQDN: git.myservermanager.com
          registryUser: ${{ secrets.FORGE_USER }}
          registryPass: ${{ secrets.FORGE_TOKEN }}
      - uses: ./.forgejo/actions/release
        name: Forgejo release
        with:
          version: ${{ inputs.version }}
          token: ${{ secrets.FORGE_TOKEN }}