on:
  push:
    branches:
      - master
  pull_request:
    types: [ opened, synchronize, reopened ]
jobs:
  test:
    # tooling is available natively
    runs-on: native
    steps:
      - uses: actions/checkout@v3
        name: Checkout
      - uses: ./.forgejo/actions/oci-prepare
        name: OCI prepare
      - uses: ./.forgejo/actions/oci-build
        name: OCI build
      - uses: ./.forgejo/actions/oci-test-integration
        name: OCI test integration
        with:
          image: varakh/upda:${{ github.sha }}