on:
  push:
    branches:
      - master
  pull_request:
    types: [ opened, synchronize, reopened ]
jobs:
  test:
    # tooling is available natively
    runs-on: native
    steps:
      - uses: actions/checkout@v3
        name: Checkout
      - uses: ./.forgejo/actions/oci-prepare
        name: OCI - prepare
      - name: Test - prepare
        shell: bash
        run: |
          make clean dependencies
      - uses: ./.forgejo/actions/test
        name: Test - run