{
 "title": "upda",
 "description": "upda",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "job",
    "query": "label_values(go_goroutines, job)"
   },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(go_goroutines{job=\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "upda", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Updates",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "upda_updates_all{job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "upda_updates_pending{job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Pending"
    },
    {
     "expr": "upda_updates_approved{job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Approved"
    },
    {
     "expr": "upda_updates_ignored{job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Ignored"
    }
   ]
  },
  {
   "title": "Updates Details",
   "type": "stat",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "upda_updates{job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{application}} {{host}} {{provider}}"
    }
   ]
  },
  {
   "title": "Events",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "upda_events{job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Webhooks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "upda_webhooks{job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Request Count per status code",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "promhttp_metric_handler_requests_total{job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Request Duration Count",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "upda_request_duration_count{job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{method}} | {{path}}"
    }
   ]
  },
  {
   "title": "Sum Request Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "upda_request_size_bytes_sum{job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sum Response Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "upda_response_size_bytes_sum{job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests in flight",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "promhttp_metric_handler_requests_in_flight{job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Total",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "upda_requests_total{job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{code}} | {{method}} | {{path}}"
    }
   ]
  },
  {
   "title": "Avg. Size / Request",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(upda_request_size_bytes_sum{job=\"$job\", instance=~\"$instance\"})/upda_request_size_bytes_count{job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg. Size / Response",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(upda_response_size_bytes_sum{job=\"$job\", instance=~\"$instance\"})/upda_response_size_bytes_count{job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests with error",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "promhttp_metric_handler_errors_total{job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Runtime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Memory in Off-Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_mspan_inuse_bytes{job=\"$job\", instance=~\"$instance\"}"
    },
    {
     "expr": "go_memstats_mspan_sys_bytes{job=\"$job\", instance=~\"$instance\"}"
    },
    {
     "expr": "go_memstats_mcache_inuse_bytes{job=\"$job\", instance=~\"$instance\"}"
    },
    {
     "expr": "go_memstats_mcache_sys_bytes{job=\"$job\", instance=~\"$instance\"}"
    },
    {
     "expr": "go_memstats_buck_hash_sys_bytes{job=\"$job\", instance=~\"$instance\"}"
    },
    {
     "expr": "go_memstats_gc_sys_bytes{job=\"$job\", instance=~\"$instance\"}"
    },
    {
     "expr": "go_memstats_other_sys_bytes{job=\"$job\", instance=~\"$instance\"} - go_memstats_other_sys_bytes{job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "bytes of memory are used for other runtime allocations {instance={{instance}}}"
    },
    {
     "expr": "go_memstats_next_gc_bytes{job=\"$job\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Memory in Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{job=\"$job\", instance=~\"$instance\"}"
    },
    {
     "expr": "go_memstats_heap_sys_bytes{job=\"$job\", instance=~\"$instance\"}"
    },
    {
     "expr": "go_memstats_heap_idle_bytes{job=\"$job\", instance=~\"$instance\"}"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"$job\", instance=~\"$instance\"}"
    },
    {
     "expr": "go_memstats_heap_released_bytes{job=\"$job\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Memory in Stack",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_stack_inuse_bytes{job=\"$job\", instance=~\"$instance\"}"
    },
    {
     "expr": "go_memstats_stack_sys_bytes{job=\"$job\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Total Used Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{job=\"$job\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Number of Live Objects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_memstats_mallocs_total{job=\"$job\", instance=~\"$instance\"} - go_memstats_frees_total{job=\"$job\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Rate of Objects Allocated",
   "type": "timeseries",
   "description": "shows how many heap objects are allocated. This is a counter value so you can use rate() to objects allocated/s.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(go_memstats_mallocs_total{job=\"$job\", instance=~\"$instance\"}[1m])"
    }
   ]
  },
  {
   "title": "Rate of a Pointer Dereferences",
   "type": "timeseries",
   "description": "go_memstats_lookups_total – counts how many pointer dereferences happened. This is a counter value so you can use rate() to lookups/s.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(go_memstats_lookups_total{job=\"$job\", instance=~\"$instance\"}[1m])"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{job=\"$job\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Rates of Allocation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=\"$job\", instance=~\"$instance\"}[1m])"
    }
   ]
  },
  {
   "title": "GC duration quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=\"$job\", instance=~\"$instance\"}"
    }
   ]
  }
 ]
}