runs:
  using: "composite"
  steps:
    - name: Tooling - set up node
      uses: actions/setup-node@v6
      with:
        node-version: 24
    - name: Tooling - set up pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10
    - name: Tooling - set up Go
      uses: actions/setup-go@v6
      with:
        go-version: '^1.25'