inputs:
  loadImage:
    description: "load image, so it's available after build and thus not automatically removed"
    required: true
    type: boolean
runs:
  using: "composite"
  steps:
    - name: OCI - build
      uses: docker/build-push-action@v4
      with:
        push: false
        context: .
        load: ${{ inputs.loadImage }}
        no-cache: true
        build-args: |
          VERSION=${{ github.sha }}
        tags: |
          varakh/upda:${{ github.sha }}
