runs:
  using: "composite"
  steps:
    - name: OCI - [SERVER] build
      uses: docker/build-push-action@v4
      with:
        push: false
        context: .
        load: true
        no-cache: true
        build-args: |
          VERSION=${{ github.sha }}
        tags: |
          varakh/upda:${{ github.sha }}

    - name: OCI - [STANDALONE_WEB_INTERFACE] build"
      uses: docker/build-push-action@v4
      with:
        push: false
        context: ./server/web/
        load: true
        no-cache: true
        tags: |
          varakh/upda-standalone-webinterface:${{ github.sha }}