runs:
  using: "composite"
  steps:
    - name: OCI - build
      shell: bash
      run: |
        docker buildx build --no-cache -t git.myservermanager.com/varakh/upda:${{ github.sha }} -f Dockerfile .
