{
 "title": "upda",
 "description": "upda",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(upda_webhooks,job)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(upda_webhooks{job=\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Updates",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "upda_updates_all{job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "upda_updates_pending{job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Pending"
    },
    {
     "expr": "upda_updates_approved{job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Approved"
    },
    {
     "expr": "upda_updates_ignored{job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Ignored"
    }
   ]
  },
  {
   "title": "Events",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "upda_events{job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Webhooks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "upda_webhooks{job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Actions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "upda_actions{job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}