// Code generated by go-enum DO NOT EDIT.
// Version: 0.9.2
// Revision: 9d73c76728916582359433d1eb0b27340a8268b7
// Build Date: 2025-10-17T20:10:48Z
// Built By: goreleaser

package constant

import (
	"fmt"
	"strings"
)

const (
	// ActionInvocationStateCreated is a ActionInvocationState of type created.
	ActionInvocationStateCreated ActionInvocationState = "created"
	// ActionInvocationStateRunning is a ActionInvocationState of type running.
	ActionInvocationStateRunning ActionInvocationState = "running"
	// ActionInvocationStateRetrying is a ActionInvocationState of type retrying.
	ActionInvocationStateRetrying ActionInvocationState = "retrying"
	// ActionInvocationStateSuccess is a ActionInvocationState of type success.
	ActionInvocationStateSuccess ActionInvocationState = "success"
	// ActionInvocationStateError is a ActionInvocationState of type error.
	ActionInvocationStateError ActionInvocationState = "error"
)

var ErrInvalidActionInvocationState = fmt.Errorf("not a valid ActionInvocationState, try [%s]", strings.Join(_ActionInvocationStateNames, ", "))

var _ActionInvocationStateNames = []string{
	string(ActionInvocationStateCreated),
	string(ActionInvocationStateRunning),
	string(ActionInvocationStateRetrying),
	string(ActionInvocationStateSuccess),
	string(ActionInvocationStateError),
}

// ActionInvocationStateNames returns a list of possible string values of ActionInvocationState.
func ActionInvocationStateNames() []string {
	tmp := make([]string, len(_ActionInvocationStateNames))
	copy(tmp, _ActionInvocationStateNames)
	return tmp
}

// ActionInvocationStateValues returns a list of the values for ActionInvocationState
func ActionInvocationStateValues() []ActionInvocationState {
	return []ActionInvocationState{
		ActionInvocationStateCreated,
		ActionInvocationStateRunning,
		ActionInvocationStateRetrying,
		ActionInvocationStateSuccess,
		ActionInvocationStateError,
	}
}

// String implements the Stringer interface.
func (x ActionInvocationState) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ActionInvocationState) IsValid() bool {
	_, err := ParseActionInvocationState(string(x))
	return err == nil
}

var _ActionInvocationStateValue = map[string]ActionInvocationState{
	"created":  ActionInvocationStateCreated,
	"running":  ActionInvocationStateRunning,
	"retrying": ActionInvocationStateRetrying,
	"success":  ActionInvocationStateSuccess,
	"error":    ActionInvocationStateError,
}

// ParseActionInvocationState attempts to convert a string to a ActionInvocationState.
func ParseActionInvocationState(name string) (ActionInvocationState, error) {
	if x, ok := _ActionInvocationStateValue[name]; ok {
		return x, nil
	}
	return ActionInvocationState(""), fmt.Errorf("%s is %w", name, ErrInvalidActionInvocationState)
}

// MustParseActionInvocationState converts a string to a ActionInvocationState, and panics if is not valid.
func MustParseActionInvocationState(name string) ActionInvocationState {
	val, err := ParseActionInvocationState(name)
	if err != nil {
		panic(err)
	}
	return val
}

// MarshalText implements the text marshaller method.
func (x ActionInvocationState) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *ActionInvocationState) UnmarshalText(text []byte) error {
	tmp, err := ParseActionInvocationState(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *ActionInvocationState) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

const (
	// ActionTypeShoutrrr is a ActionType of type shoutrrr.
	ActionTypeShoutrrr ActionType = "shoutrrr"
)

var ErrInvalidActionType = fmt.Errorf("not a valid ActionType, try [%s]", strings.Join(_ActionTypeNames, ", "))

var _ActionTypeNames = []string{
	string(ActionTypeShoutrrr),
}

// ActionTypeNames returns a list of possible string values of ActionType.
func ActionTypeNames() []string {
	tmp := make([]string, len(_ActionTypeNames))
	copy(tmp, _ActionTypeNames)
	return tmp
}

// ActionTypeValues returns a list of the values for ActionType
func ActionTypeValues() []ActionType {
	return []ActionType{
		ActionTypeShoutrrr,
	}
}

// String implements the Stringer interface.
func (x ActionType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ActionType) IsValid() bool {
	_, err := ParseActionType(string(x))
	return err == nil
}

var _ActionTypeValue = map[string]ActionType{
	"shoutrrr": ActionTypeShoutrrr,
}

// ParseActionType attempts to convert a string to a ActionType.
func ParseActionType(name string) (ActionType, error) {
	if x, ok := _ActionTypeValue[name]; ok {
		return x, nil
	}
	return ActionType(""), fmt.Errorf("%s is %w", name, ErrInvalidActionType)
}

// MustParseActionType converts a string to a ActionType, and panics if is not valid.
func MustParseActionType(name string) ActionType {
	val, err := ParseActionType(name)
	if err != nil {
		panic(err)
	}
	return val
}

// MarshalText implements the text marshaller method.
func (x ActionType) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *ActionType) UnmarshalText(text []byte) error {
	tmp, err := ParseActionType(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *ActionType) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

const (
	// ConfigAuthSessionProviderSingle is a ConfigAuthSessionProvider of type single.
	ConfigAuthSessionProviderSingle ConfigAuthSessionProvider = "single"
	// ConfigAuthSessionProviderCredentials is a ConfigAuthSessionProvider of type credentials.
	ConfigAuthSessionProviderCredentials ConfigAuthSessionProvider = "credentials"
)

var ErrInvalidConfigAuthSessionProvider = fmt.Errorf("not a valid ConfigAuthSessionProvider, try [%s]", strings.Join(_ConfigAuthSessionProviderNames, ", "))

var _ConfigAuthSessionProviderNames = []string{
	string(ConfigAuthSessionProviderSingle),
	string(ConfigAuthSessionProviderCredentials),
}

// ConfigAuthSessionProviderNames returns a list of possible string values of ConfigAuthSessionProvider.
func ConfigAuthSessionProviderNames() []string {
	tmp := make([]string, len(_ConfigAuthSessionProviderNames))
	copy(tmp, _ConfigAuthSessionProviderNames)
	return tmp
}

// ConfigAuthSessionProviderValues returns a list of the values for ConfigAuthSessionProvider
func ConfigAuthSessionProviderValues() []ConfigAuthSessionProvider {
	return []ConfigAuthSessionProvider{
		ConfigAuthSessionProviderSingle,
		ConfigAuthSessionProviderCredentials,
	}
}

// String implements the Stringer interface.
func (x ConfigAuthSessionProvider) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ConfigAuthSessionProvider) IsValid() bool {
	_, err := ParseConfigAuthSessionProvider(string(x))
	return err == nil
}

var _ConfigAuthSessionProviderValue = map[string]ConfigAuthSessionProvider{
	"single":      ConfigAuthSessionProviderSingle,
	"credentials": ConfigAuthSessionProviderCredentials,
}

// ParseConfigAuthSessionProvider attempts to convert a string to a ConfigAuthSessionProvider.
func ParseConfigAuthSessionProvider(name string) (ConfigAuthSessionProvider, error) {
	if x, ok := _ConfigAuthSessionProviderValue[name]; ok {
		return x, nil
	}
	return ConfigAuthSessionProvider(""), fmt.Errorf("%s is %w", name, ErrInvalidConfigAuthSessionProvider)
}

// MustParseConfigAuthSessionProvider converts a string to a ConfigAuthSessionProvider, and panics if is not valid.
func MustParseConfigAuthSessionProvider(name string) ConfigAuthSessionProvider {
	val, err := ParseConfigAuthSessionProvider(name)
	if err != nil {
		panic(err)
	}
	return val
}

// MarshalText implements the text marshaller method.
func (x ConfigAuthSessionProvider) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *ConfigAuthSessionProvider) UnmarshalText(text []byte) error {
	tmp, err := ParseConfigAuthSessionProvider(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *ConfigAuthSessionProvider) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

const (
	// ConfigAuthSessionSameSiteLax is a ConfigAuthSessionSameSite of type lax.
	ConfigAuthSessionSameSiteLax ConfigAuthSessionSameSite = "lax"
	// ConfigAuthSessionSameSiteStrict is a ConfigAuthSessionSameSite of type strict.
	ConfigAuthSessionSameSiteStrict ConfigAuthSessionSameSite = "strict"
)

var ErrInvalidConfigAuthSessionSameSite = fmt.Errorf("not a valid ConfigAuthSessionSameSite, try [%s]", strings.Join(_ConfigAuthSessionSameSiteNames, ", "))

var _ConfigAuthSessionSameSiteNames = []string{
	string(ConfigAuthSessionSameSiteLax),
	string(ConfigAuthSessionSameSiteStrict),
}

// ConfigAuthSessionSameSiteNames returns a list of possible string values of ConfigAuthSessionSameSite.
func ConfigAuthSessionSameSiteNames() []string {
	tmp := make([]string, len(_ConfigAuthSessionSameSiteNames))
	copy(tmp, _ConfigAuthSessionSameSiteNames)
	return tmp
}

// ConfigAuthSessionSameSiteValues returns a list of the values for ConfigAuthSessionSameSite
func ConfigAuthSessionSameSiteValues() []ConfigAuthSessionSameSite {
	return []ConfigAuthSessionSameSite{
		ConfigAuthSessionSameSiteLax,
		ConfigAuthSessionSameSiteStrict,
	}
}

// String implements the Stringer interface.
func (x ConfigAuthSessionSameSite) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ConfigAuthSessionSameSite) IsValid() bool {
	_, err := ParseConfigAuthSessionSameSite(string(x))
	return err == nil
}

var _ConfigAuthSessionSameSiteValue = map[string]ConfigAuthSessionSameSite{
	"lax":    ConfigAuthSessionSameSiteLax,
	"strict": ConfigAuthSessionSameSiteStrict,
}

// ParseConfigAuthSessionSameSite attempts to convert a string to a ConfigAuthSessionSameSite.
func ParseConfigAuthSessionSameSite(name string) (ConfigAuthSessionSameSite, error) {
	if x, ok := _ConfigAuthSessionSameSiteValue[name]; ok {
		return x, nil
	}
	return ConfigAuthSessionSameSite(""), fmt.Errorf("%s is %w", name, ErrInvalidConfigAuthSessionSameSite)
}

// MustParseConfigAuthSessionSameSite converts a string to a ConfigAuthSessionSameSite, and panics if is not valid.
func MustParseConfigAuthSessionSameSite(name string) ConfigAuthSessionSameSite {
	val, err := ParseConfigAuthSessionSameSite(name)
	if err != nil {
		panic(err)
	}
	return val
}

// MarshalText implements the text marshaller method.
func (x ConfigAuthSessionSameSite) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *ConfigAuthSessionSameSite) UnmarshalText(text []byte) error {
	tmp, err := ParseConfigAuthSessionSameSite(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *ConfigAuthSessionSameSite) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

const (
	// ConfigAuthTypeSession is a ConfigAuthType of type session.
	ConfigAuthTypeSession ConfigAuthType = "session"
)

var ErrInvalidConfigAuthType = fmt.Errorf("not a valid ConfigAuthType, try [%s]", strings.Join(_ConfigAuthTypeNames, ", "))

var _ConfigAuthTypeNames = []string{
	string(ConfigAuthTypeSession),
}

// ConfigAuthTypeNames returns a list of possible string values of ConfigAuthType.
func ConfigAuthTypeNames() []string {
	tmp := make([]string, len(_ConfigAuthTypeNames))
	copy(tmp, _ConfigAuthTypeNames)
	return tmp
}

// ConfigAuthTypeValues returns a list of the values for ConfigAuthType
func ConfigAuthTypeValues() []ConfigAuthType {
	return []ConfigAuthType{
		ConfigAuthTypeSession,
	}
}

// String implements the Stringer interface.
func (x ConfigAuthType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ConfigAuthType) IsValid() bool {
	_, err := ParseConfigAuthType(string(x))
	return err == nil
}

var _ConfigAuthTypeValue = map[string]ConfigAuthType{
	"session": ConfigAuthTypeSession,
}

// ParseConfigAuthType attempts to convert a string to a ConfigAuthType.
func ParseConfigAuthType(name string) (ConfigAuthType, error) {
	if x, ok := _ConfigAuthTypeValue[name]; ok {
		return x, nil
	}
	return ConfigAuthType(""), fmt.Errorf("%s is %w", name, ErrInvalidConfigAuthType)
}

// MustParseConfigAuthType converts a string to a ConfigAuthType, and panics if is not valid.
func MustParseConfigAuthType(name string) ConfigAuthType {
	val, err := ParseConfigAuthType(name)
	if err != nil {
		panic(err)
	}
	return val
}

// MarshalText implements the text marshaller method.
func (x ConfigAuthType) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *ConfigAuthType) UnmarshalText(text []byte) error {
	tmp, err := ParseConfigAuthType(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *ConfigAuthType) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

const (
	// ConfigDatabaseTypePostgres is a ConfigDatabaseType of type postgres.
	ConfigDatabaseTypePostgres ConfigDatabaseType = "postgres"
)

var ErrInvalidConfigDatabaseType = fmt.Errorf("not a valid ConfigDatabaseType, try [%s]", strings.Join(_ConfigDatabaseTypeNames, ", "))

var _ConfigDatabaseTypeNames = []string{
	string(ConfigDatabaseTypePostgres),
}

// ConfigDatabaseTypeNames returns a list of possible string values of ConfigDatabaseType.
func ConfigDatabaseTypeNames() []string {
	tmp := make([]string, len(_ConfigDatabaseTypeNames))
	copy(tmp, _ConfigDatabaseTypeNames)
	return tmp
}

// ConfigDatabaseTypeValues returns a list of the values for ConfigDatabaseType
func ConfigDatabaseTypeValues() []ConfigDatabaseType {
	return []ConfigDatabaseType{
		ConfigDatabaseTypePostgres,
	}
}

// String implements the Stringer interface.
func (x ConfigDatabaseType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ConfigDatabaseType) IsValid() bool {
	_, err := ParseConfigDatabaseType(string(x))
	return err == nil
}

var _ConfigDatabaseTypeValue = map[string]ConfigDatabaseType{
	"postgres": ConfigDatabaseTypePostgres,
}

// ParseConfigDatabaseType attempts to convert a string to a ConfigDatabaseType.
func ParseConfigDatabaseType(name string) (ConfigDatabaseType, error) {
	if x, ok := _ConfigDatabaseTypeValue[name]; ok {
		return x, nil
	}
	return ConfigDatabaseType(""), fmt.Errorf("%s is %w", name, ErrInvalidConfigDatabaseType)
}

// MustParseConfigDatabaseType converts a string to a ConfigDatabaseType, and panics if is not valid.
func MustParseConfigDatabaseType(name string) ConfigDatabaseType {
	val, err := ParseConfigDatabaseType(name)
	if err != nil {
		panic(err)
	}
	return val
}

// MarshalText implements the text marshaller method.
func (x ConfigDatabaseType) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *ConfigDatabaseType) UnmarshalText(text []byte) error {
	tmp, err := ParseConfigDatabaseType(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *ConfigDatabaseType) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

const (
	// ConfigLogEncodingJson is a ConfigLogEncoding of type json.
	ConfigLogEncodingJson ConfigLogEncoding = "json"
	// ConfigLogEncodingConsole is a ConfigLogEncoding of type console.
	ConfigLogEncodingConsole ConfigLogEncoding = "console"
)

var ErrInvalidConfigLogEncoding = fmt.Errorf("not a valid ConfigLogEncoding, try [%s]", strings.Join(_ConfigLogEncodingNames, ", "))

var _ConfigLogEncodingNames = []string{
	string(ConfigLogEncodingJson),
	string(ConfigLogEncodingConsole),
}

// ConfigLogEncodingNames returns a list of possible string values of ConfigLogEncoding.
func ConfigLogEncodingNames() []string {
	tmp := make([]string, len(_ConfigLogEncodingNames))
	copy(tmp, _ConfigLogEncodingNames)
	return tmp
}

// ConfigLogEncodingValues returns a list of the values for ConfigLogEncoding
func ConfigLogEncodingValues() []ConfigLogEncoding {
	return []ConfigLogEncoding{
		ConfigLogEncodingJson,
		ConfigLogEncodingConsole,
	}
}

// String implements the Stringer interface.
func (x ConfigLogEncoding) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ConfigLogEncoding) IsValid() bool {
	_, err := ParseConfigLogEncoding(string(x))
	return err == nil
}

var _ConfigLogEncodingValue = map[string]ConfigLogEncoding{
	"json":    ConfigLogEncodingJson,
	"console": ConfigLogEncodingConsole,
}

// ParseConfigLogEncoding attempts to convert a string to a ConfigLogEncoding.
func ParseConfigLogEncoding(name string) (ConfigLogEncoding, error) {
	if x, ok := _ConfigLogEncodingValue[name]; ok {
		return x, nil
	}
	return ConfigLogEncoding(""), fmt.Errorf("%s is %w", name, ErrInvalidConfigLogEncoding)
}

// MustParseConfigLogEncoding converts a string to a ConfigLogEncoding, and panics if is not valid.
func MustParseConfigLogEncoding(name string) ConfigLogEncoding {
	val, err := ParseConfigLogEncoding(name)
	if err != nil {
		panic(err)
	}
	return val
}

// MarshalText implements the text marshaller method.
func (x ConfigLogEncoding) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *ConfigLogEncoding) UnmarshalText(text []byte) error {
	tmp, err := ParseConfigLogEncoding(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *ConfigLogEncoding) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

const (
	// ConfigLogTimeEncoderEpoch is a ConfigLogTimeEncoder of type epoch.
	ConfigLogTimeEncoderEpoch ConfigLogTimeEncoder = "epoch"
	// ConfigLogTimeEncoderEpochmillis is a ConfigLogTimeEncoder of type epochmillis.
	ConfigLogTimeEncoderEpochmillis ConfigLogTimeEncoder = "epochmillis"
	// ConfigLogTimeEncoderEpochnanos is a ConfigLogTimeEncoder of type epochnanos.
	ConfigLogTimeEncoderEpochnanos ConfigLogTimeEncoder = "epochnanos"
	// ConfigLogTimeEncoderIso8601 is a ConfigLogTimeEncoder of type iso8601.
	ConfigLogTimeEncoderIso8601 ConfigLogTimeEncoder = "iso8601"
	// ConfigLogTimeEncoderRfc3339 is a ConfigLogTimeEncoder of type rfc3339.
	ConfigLogTimeEncoderRfc3339 ConfigLogTimeEncoder = "rfc3339"
	// ConfigLogTimeEncoderRfc3339nano is a ConfigLogTimeEncoder of type rfc3339nano.
	ConfigLogTimeEncoderRfc3339nano ConfigLogTimeEncoder = "rfc3339nano"
)

var ErrInvalidConfigLogTimeEncoder = fmt.Errorf("not a valid ConfigLogTimeEncoder, try [%s]", strings.Join(_ConfigLogTimeEncoderNames, ", "))

var _ConfigLogTimeEncoderNames = []string{
	string(ConfigLogTimeEncoderEpoch),
	string(ConfigLogTimeEncoderEpochmillis),
	string(ConfigLogTimeEncoderEpochnanos),
	string(ConfigLogTimeEncoderIso8601),
	string(ConfigLogTimeEncoderRfc3339),
	string(ConfigLogTimeEncoderRfc3339nano),
}

// ConfigLogTimeEncoderNames returns a list of possible string values of ConfigLogTimeEncoder.
func ConfigLogTimeEncoderNames() []string {
	tmp := make([]string, len(_ConfigLogTimeEncoderNames))
	copy(tmp, _ConfigLogTimeEncoderNames)
	return tmp
}

// ConfigLogTimeEncoderValues returns a list of the values for ConfigLogTimeEncoder
func ConfigLogTimeEncoderValues() []ConfigLogTimeEncoder {
	return []ConfigLogTimeEncoder{
		ConfigLogTimeEncoderEpoch,
		ConfigLogTimeEncoderEpochmillis,
		ConfigLogTimeEncoderEpochnanos,
		ConfigLogTimeEncoderIso8601,
		ConfigLogTimeEncoderRfc3339,
		ConfigLogTimeEncoderRfc3339nano,
	}
}

// String implements the Stringer interface.
func (x ConfigLogTimeEncoder) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ConfigLogTimeEncoder) IsValid() bool {
	_, err := ParseConfigLogTimeEncoder(string(x))
	return err == nil
}

var _ConfigLogTimeEncoderValue = map[string]ConfigLogTimeEncoder{
	"epoch":       ConfigLogTimeEncoderEpoch,
	"epochmillis": ConfigLogTimeEncoderEpochmillis,
	"epochnanos":  ConfigLogTimeEncoderEpochnanos,
	"iso8601":     ConfigLogTimeEncoderIso8601,
	"rfc3339":     ConfigLogTimeEncoderRfc3339,
	"rfc3339nano": ConfigLogTimeEncoderRfc3339nano,
}

// ParseConfigLogTimeEncoder attempts to convert a string to a ConfigLogTimeEncoder.
func ParseConfigLogTimeEncoder(name string) (ConfigLogTimeEncoder, error) {
	if x, ok := _ConfigLogTimeEncoderValue[name]; ok {
		return x, nil
	}
	return ConfigLogTimeEncoder(""), fmt.Errorf("%s is %w", name, ErrInvalidConfigLogTimeEncoder)
}

// MustParseConfigLogTimeEncoder converts a string to a ConfigLogTimeEncoder, and panics if is not valid.
func MustParseConfigLogTimeEncoder(name string) ConfigLogTimeEncoder {
	val, err := ParseConfigLogTimeEncoder(name)
	if err != nil {
		panic(err)
	}
	return val
}

// MarshalText implements the text marshaller method.
func (x ConfigLogTimeEncoder) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *ConfigLogTimeEncoder) UnmarshalText(text []byte) error {
	tmp, err := ParseConfigLogTimeEncoder(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *ConfigLogTimeEncoder) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

const (
	// EventNameUpdateCreated is a EventName of type update_created.
	EventNameUpdateCreated EventName = "update_created"
	// EventNameUpdateUpdated is a EventName of type update_updated.
	EventNameUpdateUpdated EventName = "update_updated"
	// EventNameUpdateUpdatedState is a EventName of type update_updated_state.
	EventNameUpdateUpdatedState EventName = "update_updated_state"
	// EventNameUpdateUpdatedVersion is a EventName of type update_updated_version.
	EventNameUpdateUpdatedVersion EventName = "update_updated_version"
	// EventNameUpdateDeleted is a EventName of type update_deleted.
	EventNameUpdateDeleted EventName = "update_deleted"
	// EventNameCommentCreated is a EventName of type comment_created.
	EventNameCommentCreated EventName = "comment_created"
)

var ErrInvalidEventName = fmt.Errorf("not a valid EventName, try [%s]", strings.Join(_EventNameNames, ", "))

var _EventNameNames = []string{
	string(EventNameUpdateCreated),
	string(EventNameUpdateUpdated),
	string(EventNameUpdateUpdatedState),
	string(EventNameUpdateUpdatedVersion),
	string(EventNameUpdateDeleted),
	string(EventNameCommentCreated),
}

// EventNameNames returns a list of possible string values of EventName.
func EventNameNames() []string {
	tmp := make([]string, len(_EventNameNames))
	copy(tmp, _EventNameNames)
	return tmp
}

// EventNameValues returns a list of the values for EventName
func EventNameValues() []EventName {
	return []EventName{
		EventNameUpdateCreated,
		EventNameUpdateUpdated,
		EventNameUpdateUpdatedState,
		EventNameUpdateUpdatedVersion,
		EventNameUpdateDeleted,
		EventNameCommentCreated,
	}
}

// String implements the Stringer interface.
func (x EventName) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x EventName) IsValid() bool {
	_, err := ParseEventName(string(x))
	return err == nil
}

var _EventNameValue = map[string]EventName{
	"update_created":         EventNameUpdateCreated,
	"update_updated":         EventNameUpdateUpdated,
	"update_updated_state":   EventNameUpdateUpdatedState,
	"update_updated_version": EventNameUpdateUpdatedVersion,
	"update_deleted":         EventNameUpdateDeleted,
	"comment_created":        EventNameCommentCreated,
}

// ParseEventName attempts to convert a string to a EventName.
func ParseEventName(name string) (EventName, error) {
	if x, ok := _EventNameValue[name]; ok {
		return x, nil
	}
	return EventName(""), fmt.Errorf("%s is %w", name, ErrInvalidEventName)
}

// MustParseEventName converts a string to a EventName, and panics if is not valid.
func MustParseEventName(name string) EventName {
	val, err := ParseEventName(name)
	if err != nil {
		panic(err)
	}
	return val
}

// MarshalText implements the text marshaller method.
func (x EventName) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *EventName) UnmarshalText(text []byte) error {
	tmp, err := ParseEventName(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *EventName) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

const (
	// EventStateCreated is a EventState of type created.
	EventStateCreated EventState = "created"
	// EventStateEnqueued is a EventState of type enqueued.
	EventStateEnqueued EventState = "enqueued"
)

var ErrInvalidEventState = fmt.Errorf("not a valid EventState, try [%s]", strings.Join(_EventStateNames, ", "))

var _EventStateNames = []string{
	string(EventStateCreated),
	string(EventStateEnqueued),
}

// EventStateNames returns a list of possible string values of EventState.
func EventStateNames() []string {
	tmp := make([]string, len(_EventStateNames))
	copy(tmp, _EventStateNames)
	return tmp
}

// EventStateValues returns a list of the values for EventState
func EventStateValues() []EventState {
	return []EventState{
		EventStateCreated,
		EventStateEnqueued,
	}
}

// String implements the Stringer interface.
func (x EventState) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x EventState) IsValid() bool {
	_, err := ParseEventState(string(x))
	return err == nil
}

var _EventStateValue = map[string]EventState{
	"created":  EventStateCreated,
	"enqueued": EventStateEnqueued,
}

// ParseEventState attempts to convert a string to a EventState.
func ParseEventState(name string) (EventState, error) {
	if x, ok := _EventStateValue[name]; ok {
		return x, nil
	}
	return EventState(""), fmt.Errorf("%s is %w", name, ErrInvalidEventState)
}

// MustParseEventState converts a string to a EventState, and panics if is not valid.
func MustParseEventState(name string) EventState {
	val, err := ParseEventState(name)
	if err != nil {
		panic(err)
	}
	return val
}

// MarshalText implements the text marshaller method.
func (x EventState) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *EventState) UnmarshalText(text []byte) error {
	tmp, err := ParseEventState(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *EventState) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

const (
	// FilterPresetTypeUpdate is a FilterPresetType of type update.
	FilterPresetTypeUpdate FilterPresetType = "update"
)

var ErrInvalidFilterPresetType = fmt.Errorf("not a valid FilterPresetType, try [%s]", strings.Join(_FilterPresetTypeNames, ", "))

var _FilterPresetTypeNames = []string{
	string(FilterPresetTypeUpdate),
}

// FilterPresetTypeNames returns a list of possible string values of FilterPresetType.
func FilterPresetTypeNames() []string {
	tmp := make([]string, len(_FilterPresetTypeNames))
	copy(tmp, _FilterPresetTypeNames)
	return tmp
}

// FilterPresetTypeValues returns a list of the values for FilterPresetType
func FilterPresetTypeValues() []FilterPresetType {
	return []FilterPresetType{
		FilterPresetTypeUpdate,
	}
}

// String implements the Stringer interface.
func (x FilterPresetType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x FilterPresetType) IsValid() bool {
	_, err := ParseFilterPresetType(string(x))
	return err == nil
}

var _FilterPresetTypeValue = map[string]FilterPresetType{
	"update": FilterPresetTypeUpdate,
}

// ParseFilterPresetType attempts to convert a string to a FilterPresetType.
func ParseFilterPresetType(name string) (FilterPresetType, error) {
	if x, ok := _FilterPresetTypeValue[name]; ok {
		return x, nil
	}
	return FilterPresetType(""), fmt.Errorf("%s is %w", name, ErrInvalidFilterPresetType)
}

// MustParseFilterPresetType converts a string to a FilterPresetType, and panics if is not valid.
func MustParseFilterPresetType(name string) FilterPresetType {
	val, err := ParseFilterPresetType(name)
	if err != nil {
		panic(err)
	}
	return val
}

// MarshalText implements the text marshaller method.
func (x FilterPresetType) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *FilterPresetType) UnmarshalText(text []byte) error {
	tmp, err := ParseFilterPresetType(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *FilterPresetType) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

const (
	// WebhookTypeGeneric is a WebhookType of type generic.
	WebhookTypeGeneric WebhookType = "generic"
	// WebhookTypeDiun is a WebhookType of type diun.
	WebhookTypeDiun WebhookType = "diun"
)

var ErrInvalidWebhookType = fmt.Errorf("not a valid WebhookType, try [%s]", strings.Join(_WebhookTypeNames, ", "))

var _WebhookTypeNames = []string{
	string(WebhookTypeGeneric),
	string(WebhookTypeDiun),
}

// WebhookTypeNames returns a list of possible string values of WebhookType.
func WebhookTypeNames() []string {
	tmp := make([]string, len(_WebhookTypeNames))
	copy(tmp, _WebhookTypeNames)
	return tmp
}

// WebhookTypeValues returns a list of the values for WebhookType
func WebhookTypeValues() []WebhookType {
	return []WebhookType{
		WebhookTypeGeneric,
		WebhookTypeDiun,
	}
}

// String implements the Stringer interface.
func (x WebhookType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x WebhookType) IsValid() bool {
	_, err := ParseWebhookType(string(x))
	return err == nil
}

var _WebhookTypeValue = map[string]WebhookType{
	"generic": WebhookTypeGeneric,
	"diun":    WebhookTypeDiun,
}

// ParseWebhookType attempts to convert a string to a WebhookType.
func ParseWebhookType(name string) (WebhookType, error) {
	if x, ok := _WebhookTypeValue[name]; ok {
		return x, nil
	}
	return WebhookType(""), fmt.Errorf("%s is %w", name, ErrInvalidWebhookType)
}

// MustParseWebhookType converts a string to a WebhookType, and panics if is not valid.
func MustParseWebhookType(name string) WebhookType {
	val, err := ParseWebhookType(name)
	if err != nil {
		panic(err)
	}
	return val
}

// MarshalText implements the text marshaller method.
func (x WebhookType) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *WebhookType) UnmarshalText(text []byte) error {
	tmp, err := ParseWebhookType(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *WebhookType) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}
