// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package constant

import (
	"fmt"
	"strings"
)

const (
	// ActionInvocationStateCreated is a ActionInvocationState of type created.
	ActionInvocationStateCreated ActionInvocationState = "created"
	// ActionInvocationStateRunning is a ActionInvocationState of type running.
	ActionInvocationStateRunning ActionInvocationState = "running"
	// ActionInvocationStateRetrying is a ActionInvocationState of type retrying.
	ActionInvocationStateRetrying ActionInvocationState = "retrying"
	// ActionInvocationStateSuccess is a ActionInvocationState of type success.
	ActionInvocationStateSuccess ActionInvocationState = "success"
	// ActionInvocationStateError is a ActionInvocationState of type error.
	ActionInvocationStateError ActionInvocationState = "error"
)

var ErrInvalidActionInvocationState = fmt.Errorf("not a valid ActionInvocationState, try [%s]", strings.Join(_ActionInvocationStateNames, ", "))

var _ActionInvocationStateNames = []string{
	string(ActionInvocationStateCreated),
	string(ActionInvocationStateRunning),
	string(ActionInvocationStateRetrying),
	string(ActionInvocationStateSuccess),
	string(ActionInvocationStateError),
}

// ActionInvocationStateNames returns a list of possible string values of ActionInvocationState.
func ActionInvocationStateNames() []string {
	tmp := make([]string, len(_ActionInvocationStateNames))
	copy(tmp, _ActionInvocationStateNames)
	return tmp
}

// ActionInvocationStateValues returns a list of the values for ActionInvocationState
func ActionInvocationStateValues() []ActionInvocationState {
	return []ActionInvocationState{
		ActionInvocationStateCreated,
		ActionInvocationStateRunning,
		ActionInvocationStateRetrying,
		ActionInvocationStateSuccess,
		ActionInvocationStateError,
	}
}

// String implements the Stringer interface.
func (x ActionInvocationState) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ActionInvocationState) IsValid() bool {
	_, err := ParseActionInvocationState(string(x))
	return err == nil
}

var _ActionInvocationStateValue = map[string]ActionInvocationState{
	"created":  ActionInvocationStateCreated,
	"running":  ActionInvocationStateRunning,
	"retrying": ActionInvocationStateRetrying,
	"success":  ActionInvocationStateSuccess,
	"error":    ActionInvocationStateError,
}

// ParseActionInvocationState attempts to convert a string to a ActionInvocationState.
func ParseActionInvocationState(name string) (ActionInvocationState, error) {
	if x, ok := _ActionInvocationStateValue[name]; ok {
		return x, nil
	}
	return ActionInvocationState(""), fmt.Errorf("%s is %w", name, ErrInvalidActionInvocationState)
}

// MustParseActionInvocationState converts a string to a ActionInvocationState, and panics if is not valid.
func MustParseActionInvocationState(name string) ActionInvocationState {
	val, err := ParseActionInvocationState(name)
	if err != nil {
		panic(err)
	}
	return val
}

// MarshalText implements the text marshaller method.
func (x ActionInvocationState) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *ActionInvocationState) UnmarshalText(text []byte) error {
	tmp, err := ParseActionInvocationState(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

const (
	// ActionTypeShoutrrr is a ActionType of type shoutrrr.
	ActionTypeShoutrrr ActionType = "shoutrrr"
)

var ErrInvalidActionType = fmt.Errorf("not a valid ActionType, try [%s]", strings.Join(_ActionTypeNames, ", "))

var _ActionTypeNames = []string{
	string(ActionTypeShoutrrr),
}

// ActionTypeNames returns a list of possible string values of ActionType.
func ActionTypeNames() []string {
	tmp := make([]string, len(_ActionTypeNames))
	copy(tmp, _ActionTypeNames)
	return tmp
}

// ActionTypeValues returns a list of the values for ActionType
func ActionTypeValues() []ActionType {
	return []ActionType{
		ActionTypeShoutrrr,
	}
}

// String implements the Stringer interface.
func (x ActionType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ActionType) IsValid() bool {
	_, err := ParseActionType(string(x))
	return err == nil
}

var _ActionTypeValue = map[string]ActionType{
	"shoutrrr": ActionTypeShoutrrr,
}

// ParseActionType attempts to convert a string to a ActionType.
func ParseActionType(name string) (ActionType, error) {
	if x, ok := _ActionTypeValue[name]; ok {
		return x, nil
	}
	return ActionType(""), fmt.Errorf("%s is %w", name, ErrInvalidActionType)
}

// MustParseActionType converts a string to a ActionType, and panics if is not valid.
func MustParseActionType(name string) ActionType {
	val, err := ParseActionType(name)
	if err != nil {
		panic(err)
	}
	return val
}

// MarshalText implements the text marshaller method.
func (x ActionType) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *ActionType) UnmarshalText(text []byte) error {
	tmp, err := ParseActionType(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

const (
	// ConfigAuthModeBasicSingle is a ConfigAuthMode of type basic_single.
	ConfigAuthModeBasicSingle ConfigAuthMode = "basic_single"
	// ConfigAuthModeBasicCredentials is a ConfigAuthMode of type basic_credentials.
	ConfigAuthModeBasicCredentials ConfigAuthMode = "basic_credentials"
)

var ErrInvalidConfigAuthMode = fmt.Errorf("not a valid ConfigAuthMode, try [%s]", strings.Join(_ConfigAuthModeNames, ", "))

var _ConfigAuthModeNames = []string{
	string(ConfigAuthModeBasicSingle),
	string(ConfigAuthModeBasicCredentials),
}

// ConfigAuthModeNames returns a list of possible string values of ConfigAuthMode.
func ConfigAuthModeNames() []string {
	tmp := make([]string, len(_ConfigAuthModeNames))
	copy(tmp, _ConfigAuthModeNames)
	return tmp
}

// ConfigAuthModeValues returns a list of the values for ConfigAuthMode
func ConfigAuthModeValues() []ConfigAuthMode {
	return []ConfigAuthMode{
		ConfigAuthModeBasicSingle,
		ConfigAuthModeBasicCredentials,
	}
}

// String implements the Stringer interface.
func (x ConfigAuthMode) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ConfigAuthMode) IsValid() bool {
	_, err := ParseConfigAuthMode(string(x))
	return err == nil
}

var _ConfigAuthModeValue = map[string]ConfigAuthMode{
	"basic_single":      ConfigAuthModeBasicSingle,
	"basic_credentials": ConfigAuthModeBasicCredentials,
}

// ParseConfigAuthMode attempts to convert a string to a ConfigAuthMode.
func ParseConfigAuthMode(name string) (ConfigAuthMode, error) {
	if x, ok := _ConfigAuthModeValue[name]; ok {
		return x, nil
	}
	return ConfigAuthMode(""), fmt.Errorf("%s is %w", name, ErrInvalidConfigAuthMode)
}

// MustParseConfigAuthMode converts a string to a ConfigAuthMode, and panics if is not valid.
func MustParseConfigAuthMode(name string) ConfigAuthMode {
	val, err := ParseConfigAuthMode(name)
	if err != nil {
		panic(err)
	}
	return val
}

// MarshalText implements the text marshaller method.
func (x ConfigAuthMode) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *ConfigAuthMode) UnmarshalText(text []byte) error {
	tmp, err := ParseConfigAuthMode(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

const (
	// ConfigDatabaseTypePostgres is a ConfigDatabaseType of type postgres.
	ConfigDatabaseTypePostgres ConfigDatabaseType = "postgres"
)

var ErrInvalidConfigDatabaseType = fmt.Errorf("not a valid ConfigDatabaseType, try [%s]", strings.Join(_ConfigDatabaseTypeNames, ", "))

var _ConfigDatabaseTypeNames = []string{
	string(ConfigDatabaseTypePostgres),
}

// ConfigDatabaseTypeNames returns a list of possible string values of ConfigDatabaseType.
func ConfigDatabaseTypeNames() []string {
	tmp := make([]string, len(_ConfigDatabaseTypeNames))
	copy(tmp, _ConfigDatabaseTypeNames)
	return tmp
}

// ConfigDatabaseTypeValues returns a list of the values for ConfigDatabaseType
func ConfigDatabaseTypeValues() []ConfigDatabaseType {
	return []ConfigDatabaseType{
		ConfigDatabaseTypePostgres,
	}
}

// String implements the Stringer interface.
func (x ConfigDatabaseType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ConfigDatabaseType) IsValid() bool {
	_, err := ParseConfigDatabaseType(string(x))
	return err == nil
}

var _ConfigDatabaseTypeValue = map[string]ConfigDatabaseType{
	"postgres": ConfigDatabaseTypePostgres,
}

// ParseConfigDatabaseType attempts to convert a string to a ConfigDatabaseType.
func ParseConfigDatabaseType(name string) (ConfigDatabaseType, error) {
	if x, ok := _ConfigDatabaseTypeValue[name]; ok {
		return x, nil
	}
	return ConfigDatabaseType(""), fmt.Errorf("%s is %w", name, ErrInvalidConfigDatabaseType)
}

// MustParseConfigDatabaseType converts a string to a ConfigDatabaseType, and panics if is not valid.
func MustParseConfigDatabaseType(name string) ConfigDatabaseType {
	val, err := ParseConfigDatabaseType(name)
	if err != nil {
		panic(err)
	}
	return val
}

// MarshalText implements the text marshaller method.
func (x ConfigDatabaseType) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *ConfigDatabaseType) UnmarshalText(text []byte) error {
	tmp, err := ParseConfigDatabaseType(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

const (
	// ConfigLogCallerEncoderFull is a ConfigLogCallerEncoder of type full.
	ConfigLogCallerEncoderFull ConfigLogCallerEncoder = "full"
	// ConfigLogCallerEncoderShort is a ConfigLogCallerEncoder of type short.
	ConfigLogCallerEncoderShort ConfigLogCallerEncoder = "short"
)

var ErrInvalidConfigLogCallerEncoder = fmt.Errorf("not a valid ConfigLogCallerEncoder, try [%s]", strings.Join(_ConfigLogCallerEncoderNames, ", "))

var _ConfigLogCallerEncoderNames = []string{
	string(ConfigLogCallerEncoderFull),
	string(ConfigLogCallerEncoderShort),
}

// ConfigLogCallerEncoderNames returns a list of possible string values of ConfigLogCallerEncoder.
func ConfigLogCallerEncoderNames() []string {
	tmp := make([]string, len(_ConfigLogCallerEncoderNames))
	copy(tmp, _ConfigLogCallerEncoderNames)
	return tmp
}

// ConfigLogCallerEncoderValues returns a list of the values for ConfigLogCallerEncoder
func ConfigLogCallerEncoderValues() []ConfigLogCallerEncoder {
	return []ConfigLogCallerEncoder{
		ConfigLogCallerEncoderFull,
		ConfigLogCallerEncoderShort,
	}
}

// String implements the Stringer interface.
func (x ConfigLogCallerEncoder) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ConfigLogCallerEncoder) IsValid() bool {
	_, err := ParseConfigLogCallerEncoder(string(x))
	return err == nil
}

var _ConfigLogCallerEncoderValue = map[string]ConfigLogCallerEncoder{
	"full":  ConfigLogCallerEncoderFull,
	"short": ConfigLogCallerEncoderShort,
}

// ParseConfigLogCallerEncoder attempts to convert a string to a ConfigLogCallerEncoder.
func ParseConfigLogCallerEncoder(name string) (ConfigLogCallerEncoder, error) {
	if x, ok := _ConfigLogCallerEncoderValue[name]; ok {
		return x, nil
	}
	return ConfigLogCallerEncoder(""), fmt.Errorf("%s is %w", name, ErrInvalidConfigLogCallerEncoder)
}

// MustParseConfigLogCallerEncoder converts a string to a ConfigLogCallerEncoder, and panics if is not valid.
func MustParseConfigLogCallerEncoder(name string) ConfigLogCallerEncoder {
	val, err := ParseConfigLogCallerEncoder(name)
	if err != nil {
		panic(err)
	}
	return val
}

// MarshalText implements the text marshaller method.
func (x ConfigLogCallerEncoder) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *ConfigLogCallerEncoder) UnmarshalText(text []byte) error {
	tmp, err := ParseConfigLogCallerEncoder(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

const (
	// ConfigLogDurationEncoderSeconds is a ConfigLogDurationEncoder of type seconds.
	ConfigLogDurationEncoderSeconds ConfigLogDurationEncoder = "seconds"
	// ConfigLogDurationEncoderNanos is a ConfigLogDurationEncoder of type nanos.
	ConfigLogDurationEncoderNanos ConfigLogDurationEncoder = "nanos"
	// ConfigLogDurationEncoderMillis is a ConfigLogDurationEncoder of type millis.
	ConfigLogDurationEncoderMillis ConfigLogDurationEncoder = "millis"
	// ConfigLogDurationEncoderString is a ConfigLogDurationEncoder of type string.
	ConfigLogDurationEncoderString ConfigLogDurationEncoder = "string"
)

var ErrInvalidConfigLogDurationEncoder = fmt.Errorf("not a valid ConfigLogDurationEncoder, try [%s]", strings.Join(_ConfigLogDurationEncoderNames, ", "))

var _ConfigLogDurationEncoderNames = []string{
	string(ConfigLogDurationEncoderSeconds),
	string(ConfigLogDurationEncoderNanos),
	string(ConfigLogDurationEncoderMillis),
	string(ConfigLogDurationEncoderString),
}

// ConfigLogDurationEncoderNames returns a list of possible string values of ConfigLogDurationEncoder.
func ConfigLogDurationEncoderNames() []string {
	tmp := make([]string, len(_ConfigLogDurationEncoderNames))
	copy(tmp, _ConfigLogDurationEncoderNames)
	return tmp
}

// ConfigLogDurationEncoderValues returns a list of the values for ConfigLogDurationEncoder
func ConfigLogDurationEncoderValues() []ConfigLogDurationEncoder {
	return []ConfigLogDurationEncoder{
		ConfigLogDurationEncoderSeconds,
		ConfigLogDurationEncoderNanos,
		ConfigLogDurationEncoderMillis,
		ConfigLogDurationEncoderString,
	}
}

// String implements the Stringer interface.
func (x ConfigLogDurationEncoder) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ConfigLogDurationEncoder) IsValid() bool {
	_, err := ParseConfigLogDurationEncoder(string(x))
	return err == nil
}

var _ConfigLogDurationEncoderValue = map[string]ConfigLogDurationEncoder{
	"seconds": ConfigLogDurationEncoderSeconds,
	"nanos":   ConfigLogDurationEncoderNanos,
	"millis":  ConfigLogDurationEncoderMillis,
	"string":  ConfigLogDurationEncoderString,
}

// ParseConfigLogDurationEncoder attempts to convert a string to a ConfigLogDurationEncoder.
func ParseConfigLogDurationEncoder(name string) (ConfigLogDurationEncoder, error) {
	if x, ok := _ConfigLogDurationEncoderValue[name]; ok {
		return x, nil
	}
	return ConfigLogDurationEncoder(""), fmt.Errorf("%s is %w", name, ErrInvalidConfigLogDurationEncoder)
}

// MustParseConfigLogDurationEncoder converts a string to a ConfigLogDurationEncoder, and panics if is not valid.
func MustParseConfigLogDurationEncoder(name string) ConfigLogDurationEncoder {
	val, err := ParseConfigLogDurationEncoder(name)
	if err != nil {
		panic(err)
	}
	return val
}

// MarshalText implements the text marshaller method.
func (x ConfigLogDurationEncoder) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *ConfigLogDurationEncoder) UnmarshalText(text []byte) error {
	tmp, err := ParseConfigLogDurationEncoder(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

const (
	// ConfigLogEncodingJson is a ConfigLogEncoding of type json.
	ConfigLogEncodingJson ConfigLogEncoding = "json"
	// ConfigLogEncodingConsole is a ConfigLogEncoding of type console.
	ConfigLogEncodingConsole ConfigLogEncoding = "console"
)

var ErrInvalidConfigLogEncoding = fmt.Errorf("not a valid ConfigLogEncoding, try [%s]", strings.Join(_ConfigLogEncodingNames, ", "))

var _ConfigLogEncodingNames = []string{
	string(ConfigLogEncodingJson),
	string(ConfigLogEncodingConsole),
}

// ConfigLogEncodingNames returns a list of possible string values of ConfigLogEncoding.
func ConfigLogEncodingNames() []string {
	tmp := make([]string, len(_ConfigLogEncodingNames))
	copy(tmp, _ConfigLogEncodingNames)
	return tmp
}

// ConfigLogEncodingValues returns a list of the values for ConfigLogEncoding
func ConfigLogEncodingValues() []ConfigLogEncoding {
	return []ConfigLogEncoding{
		ConfigLogEncodingJson,
		ConfigLogEncodingConsole,
	}
}

// String implements the Stringer interface.
func (x ConfigLogEncoding) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ConfigLogEncoding) IsValid() bool {
	_, err := ParseConfigLogEncoding(string(x))
	return err == nil
}

var _ConfigLogEncodingValue = map[string]ConfigLogEncoding{
	"json":    ConfigLogEncodingJson,
	"console": ConfigLogEncodingConsole,
}

// ParseConfigLogEncoding attempts to convert a string to a ConfigLogEncoding.
func ParseConfigLogEncoding(name string) (ConfigLogEncoding, error) {
	if x, ok := _ConfigLogEncodingValue[name]; ok {
		return x, nil
	}
	return ConfigLogEncoding(""), fmt.Errorf("%s is %w", name, ErrInvalidConfigLogEncoding)
}

// MustParseConfigLogEncoding converts a string to a ConfigLogEncoding, and panics if is not valid.
func MustParseConfigLogEncoding(name string) ConfigLogEncoding {
	val, err := ParseConfigLogEncoding(name)
	if err != nil {
		panic(err)
	}
	return val
}

// MarshalText implements the text marshaller method.
func (x ConfigLogEncoding) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *ConfigLogEncoding) UnmarshalText(text []byte) error {
	tmp, err := ParseConfigLogEncoding(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

const (
	// ConfigLogLevelEncoderLowercase is a ConfigLogLevelEncoder of type lowercase.
	ConfigLogLevelEncoderLowercase ConfigLogLevelEncoder = "lowercase"
	// ConfigLogLevelEncoderLowercasecolor is a ConfigLogLevelEncoder of type lowercasecolor.
	ConfigLogLevelEncoderLowercasecolor ConfigLogLevelEncoder = "lowercasecolor"
	// ConfigLogLevelEncoderCapital is a ConfigLogLevelEncoder of type capital.
	ConfigLogLevelEncoderCapital ConfigLogLevelEncoder = "capital"
	// ConfigLogLevelEncoderCapitalcolor is a ConfigLogLevelEncoder of type capitalcolor.
	ConfigLogLevelEncoderCapitalcolor ConfigLogLevelEncoder = "capitalcolor"
)

var ErrInvalidConfigLogLevelEncoder = fmt.Errorf("not a valid ConfigLogLevelEncoder, try [%s]", strings.Join(_ConfigLogLevelEncoderNames, ", "))

var _ConfigLogLevelEncoderNames = []string{
	string(ConfigLogLevelEncoderLowercase),
	string(ConfigLogLevelEncoderLowercasecolor),
	string(ConfigLogLevelEncoderCapital),
	string(ConfigLogLevelEncoderCapitalcolor),
}

// ConfigLogLevelEncoderNames returns a list of possible string values of ConfigLogLevelEncoder.
func ConfigLogLevelEncoderNames() []string {
	tmp := make([]string, len(_ConfigLogLevelEncoderNames))
	copy(tmp, _ConfigLogLevelEncoderNames)
	return tmp
}

// ConfigLogLevelEncoderValues returns a list of the values for ConfigLogLevelEncoder
func ConfigLogLevelEncoderValues() []ConfigLogLevelEncoder {
	return []ConfigLogLevelEncoder{
		ConfigLogLevelEncoderLowercase,
		ConfigLogLevelEncoderLowercasecolor,
		ConfigLogLevelEncoderCapital,
		ConfigLogLevelEncoderCapitalcolor,
	}
}

// String implements the Stringer interface.
func (x ConfigLogLevelEncoder) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ConfigLogLevelEncoder) IsValid() bool {
	_, err := ParseConfigLogLevelEncoder(string(x))
	return err == nil
}

var _ConfigLogLevelEncoderValue = map[string]ConfigLogLevelEncoder{
	"lowercase":      ConfigLogLevelEncoderLowercase,
	"lowercasecolor": ConfigLogLevelEncoderLowercasecolor,
	"capital":        ConfigLogLevelEncoderCapital,
	"capitalcolor":   ConfigLogLevelEncoderCapitalcolor,
}

// ParseConfigLogLevelEncoder attempts to convert a string to a ConfigLogLevelEncoder.
func ParseConfigLogLevelEncoder(name string) (ConfigLogLevelEncoder, error) {
	if x, ok := _ConfigLogLevelEncoderValue[name]; ok {
		return x, nil
	}
	return ConfigLogLevelEncoder(""), fmt.Errorf("%s is %w", name, ErrInvalidConfigLogLevelEncoder)
}

// MustParseConfigLogLevelEncoder converts a string to a ConfigLogLevelEncoder, and panics if is not valid.
func MustParseConfigLogLevelEncoder(name string) ConfigLogLevelEncoder {
	val, err := ParseConfigLogLevelEncoder(name)
	if err != nil {
		panic(err)
	}
	return val
}

// MarshalText implements the text marshaller method.
func (x ConfigLogLevelEncoder) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *ConfigLogLevelEncoder) UnmarshalText(text []byte) error {
	tmp, err := ParseConfigLogLevelEncoder(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

const (
	// ConfigLogTimeEncoderEpoch is a ConfigLogTimeEncoder of type epoch.
	ConfigLogTimeEncoderEpoch ConfigLogTimeEncoder = "epoch"
	// ConfigLogTimeEncoderEpochmillis is a ConfigLogTimeEncoder of type epochmillis.
	ConfigLogTimeEncoderEpochmillis ConfigLogTimeEncoder = "epochmillis"
	// ConfigLogTimeEncoderEpochnanos is a ConfigLogTimeEncoder of type epochnanos.
	ConfigLogTimeEncoderEpochnanos ConfigLogTimeEncoder = "epochnanos"
	// ConfigLogTimeEncoderIso8601 is a ConfigLogTimeEncoder of type iso8601.
	ConfigLogTimeEncoderIso8601 ConfigLogTimeEncoder = "iso8601"
	// ConfigLogTimeEncoderRfc3339 is a ConfigLogTimeEncoder of type rfc3339.
	ConfigLogTimeEncoderRfc3339 ConfigLogTimeEncoder = "rfc3339"
	// ConfigLogTimeEncoderRfc3339nano is a ConfigLogTimeEncoder of type rfc3339nano.
	ConfigLogTimeEncoderRfc3339nano ConfigLogTimeEncoder = "rfc3339nano"
)

var ErrInvalidConfigLogTimeEncoder = fmt.Errorf("not a valid ConfigLogTimeEncoder, try [%s]", strings.Join(_ConfigLogTimeEncoderNames, ", "))

var _ConfigLogTimeEncoderNames = []string{
	string(ConfigLogTimeEncoderEpoch),
	string(ConfigLogTimeEncoderEpochmillis),
	string(ConfigLogTimeEncoderEpochnanos),
	string(ConfigLogTimeEncoderIso8601),
	string(ConfigLogTimeEncoderRfc3339),
	string(ConfigLogTimeEncoderRfc3339nano),
}

// ConfigLogTimeEncoderNames returns a list of possible string values of ConfigLogTimeEncoder.
func ConfigLogTimeEncoderNames() []string {
	tmp := make([]string, len(_ConfigLogTimeEncoderNames))
	copy(tmp, _ConfigLogTimeEncoderNames)
	return tmp
}

// ConfigLogTimeEncoderValues returns a list of the values for ConfigLogTimeEncoder
func ConfigLogTimeEncoderValues() []ConfigLogTimeEncoder {
	return []ConfigLogTimeEncoder{
		ConfigLogTimeEncoderEpoch,
		ConfigLogTimeEncoderEpochmillis,
		ConfigLogTimeEncoderEpochnanos,
		ConfigLogTimeEncoderIso8601,
		ConfigLogTimeEncoderRfc3339,
		ConfigLogTimeEncoderRfc3339nano,
	}
}

// String implements the Stringer interface.
func (x ConfigLogTimeEncoder) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ConfigLogTimeEncoder) IsValid() bool {
	_, err := ParseConfigLogTimeEncoder(string(x))
	return err == nil
}

var _ConfigLogTimeEncoderValue = map[string]ConfigLogTimeEncoder{
	"epoch":       ConfigLogTimeEncoderEpoch,
	"epochmillis": ConfigLogTimeEncoderEpochmillis,
	"epochnanos":  ConfigLogTimeEncoderEpochnanos,
	"iso8601":     ConfigLogTimeEncoderIso8601,
	"rfc3339":     ConfigLogTimeEncoderRfc3339,
	"rfc3339nano": ConfigLogTimeEncoderRfc3339nano,
}

// ParseConfigLogTimeEncoder attempts to convert a string to a ConfigLogTimeEncoder.
func ParseConfigLogTimeEncoder(name string) (ConfigLogTimeEncoder, error) {
	if x, ok := _ConfigLogTimeEncoderValue[name]; ok {
		return x, nil
	}
	return ConfigLogTimeEncoder(""), fmt.Errorf("%s is %w", name, ErrInvalidConfigLogTimeEncoder)
}

// MustParseConfigLogTimeEncoder converts a string to a ConfigLogTimeEncoder, and panics if is not valid.
func MustParseConfigLogTimeEncoder(name string) ConfigLogTimeEncoder {
	val, err := ParseConfigLogTimeEncoder(name)
	if err != nil {
		panic(err)
	}
	return val
}

// MarshalText implements the text marshaller method.
func (x ConfigLogTimeEncoder) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *ConfigLogTimeEncoder) UnmarshalText(text []byte) error {
	tmp, err := ParseConfigLogTimeEncoder(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

const (
	// EventNameUpdateCreated is a EventName of type update_created.
	EventNameUpdateCreated EventName = "update_created"
	// EventNameUpdateUpdated is a EventName of type update_updated.
	EventNameUpdateUpdated EventName = "update_updated"
	// EventNameUpdateUpdatedState is a EventName of type update_updated_state.
	EventNameUpdateUpdatedState EventName = "update_updated_state"
	// EventNameUpdateUpdatedVersion is a EventName of type update_updated_version.
	EventNameUpdateUpdatedVersion EventName = "update_updated_version"
	// EventNameUpdateDeleted is a EventName of type update_deleted.
	EventNameUpdateDeleted EventName = "update_deleted"
)

var ErrInvalidEventName = fmt.Errorf("not a valid EventName, try [%s]", strings.Join(_EventNameNames, ", "))

var _EventNameNames = []string{
	string(EventNameUpdateCreated),
	string(EventNameUpdateUpdated),
	string(EventNameUpdateUpdatedState),
	string(EventNameUpdateUpdatedVersion),
	string(EventNameUpdateDeleted),
}

// EventNameNames returns a list of possible string values of EventName.
func EventNameNames() []string {
	tmp := make([]string, len(_EventNameNames))
	copy(tmp, _EventNameNames)
	return tmp
}

// EventNameValues returns a list of the values for EventName
func EventNameValues() []EventName {
	return []EventName{
		EventNameUpdateCreated,
		EventNameUpdateUpdated,
		EventNameUpdateUpdatedState,
		EventNameUpdateUpdatedVersion,
		EventNameUpdateDeleted,
	}
}

// String implements the Stringer interface.
func (x EventName) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x EventName) IsValid() bool {
	_, err := ParseEventName(string(x))
	return err == nil
}

var _EventNameValue = map[string]EventName{
	"update_created":         EventNameUpdateCreated,
	"update_updated":         EventNameUpdateUpdated,
	"update_updated_state":   EventNameUpdateUpdatedState,
	"update_updated_version": EventNameUpdateUpdatedVersion,
	"update_deleted":         EventNameUpdateDeleted,
}

// ParseEventName attempts to convert a string to a EventName.
func ParseEventName(name string) (EventName, error) {
	if x, ok := _EventNameValue[name]; ok {
		return x, nil
	}
	return EventName(""), fmt.Errorf("%s is %w", name, ErrInvalidEventName)
}

// MustParseEventName converts a string to a EventName, and panics if is not valid.
func MustParseEventName(name string) EventName {
	val, err := ParseEventName(name)
	if err != nil {
		panic(err)
	}
	return val
}

// MarshalText implements the text marshaller method.
func (x EventName) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *EventName) UnmarshalText(text []byte) error {
	tmp, err := ParseEventName(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

const (
	// EventStateCreated is a EventState of type created.
	EventStateCreated EventState = "created"
	// EventStateEnqueued is a EventState of type enqueued.
	EventStateEnqueued EventState = "enqueued"
)

var ErrInvalidEventState = fmt.Errorf("not a valid EventState, try [%s]", strings.Join(_EventStateNames, ", "))

var _EventStateNames = []string{
	string(EventStateCreated),
	string(EventStateEnqueued),
}

// EventStateNames returns a list of possible string values of EventState.
func EventStateNames() []string {
	tmp := make([]string, len(_EventStateNames))
	copy(tmp, _EventStateNames)
	return tmp
}

// EventStateValues returns a list of the values for EventState
func EventStateValues() []EventState {
	return []EventState{
		EventStateCreated,
		EventStateEnqueued,
	}
}

// String implements the Stringer interface.
func (x EventState) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x EventState) IsValid() bool {
	_, err := ParseEventState(string(x))
	return err == nil
}

var _EventStateValue = map[string]EventState{
	"created":  EventStateCreated,
	"enqueued": EventStateEnqueued,
}

// ParseEventState attempts to convert a string to a EventState.
func ParseEventState(name string) (EventState, error) {
	if x, ok := _EventStateValue[name]; ok {
		return x, nil
	}
	return EventState(""), fmt.Errorf("%s is %w", name, ErrInvalidEventState)
}

// MustParseEventState converts a string to a EventState, and panics if is not valid.
func MustParseEventState(name string) EventState {
	val, err := ParseEventState(name)
	if err != nil {
		panic(err)
	}
	return val
}

// MarshalText implements the text marshaller method.
func (x EventState) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *EventState) UnmarshalText(text []byte) error {
	tmp, err := ParseEventState(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

const (
	// FilterPresetTypeUpdate is a FilterPresetType of type update.
	FilterPresetTypeUpdate FilterPresetType = "update"
)

var ErrInvalidFilterPresetType = fmt.Errorf("not a valid FilterPresetType, try [%s]", strings.Join(_FilterPresetTypeNames, ", "))

var _FilterPresetTypeNames = []string{
	string(FilterPresetTypeUpdate),
}

// FilterPresetTypeNames returns a list of possible string values of FilterPresetType.
func FilterPresetTypeNames() []string {
	tmp := make([]string, len(_FilterPresetTypeNames))
	copy(tmp, _FilterPresetTypeNames)
	return tmp
}

// FilterPresetTypeValues returns a list of the values for FilterPresetType
func FilterPresetTypeValues() []FilterPresetType {
	return []FilterPresetType{
		FilterPresetTypeUpdate,
	}
}

// String implements the Stringer interface.
func (x FilterPresetType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x FilterPresetType) IsValid() bool {
	_, err := ParseFilterPresetType(string(x))
	return err == nil
}

var _FilterPresetTypeValue = map[string]FilterPresetType{
	"update": FilterPresetTypeUpdate,
}

// ParseFilterPresetType attempts to convert a string to a FilterPresetType.
func ParseFilterPresetType(name string) (FilterPresetType, error) {
	if x, ok := _FilterPresetTypeValue[name]; ok {
		return x, nil
	}
	return FilterPresetType(""), fmt.Errorf("%s is %w", name, ErrInvalidFilterPresetType)
}

// MustParseFilterPresetType converts a string to a FilterPresetType, and panics if is not valid.
func MustParseFilterPresetType(name string) FilterPresetType {
	val, err := ParseFilterPresetType(name)
	if err != nil {
		panic(err)
	}
	return val
}

// MarshalText implements the text marshaller method.
func (x FilterPresetType) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *FilterPresetType) UnmarshalText(text []byte) error {
	tmp, err := ParseFilterPresetType(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

const (
	// UpdateStatePending is a UpdateState of type pending.
	UpdateStatePending UpdateState = "pending"
	// UpdateStateApproved is a UpdateState of type approved.
	UpdateStateApproved UpdateState = "approved"
	// UpdateStateIgnored is a UpdateState of type ignored.
	UpdateStateIgnored UpdateState = "ignored"
)

var ErrInvalidUpdateState = fmt.Errorf("not a valid UpdateState, try [%s]", strings.Join(_UpdateStateNames, ", "))

var _UpdateStateNames = []string{
	string(UpdateStatePending),
	string(UpdateStateApproved),
	string(UpdateStateIgnored),
}

// UpdateStateNames returns a list of possible string values of UpdateState.
func UpdateStateNames() []string {
	tmp := make([]string, len(_UpdateStateNames))
	copy(tmp, _UpdateStateNames)
	return tmp
}

// UpdateStateValues returns a list of the values for UpdateState
func UpdateStateValues() []UpdateState {
	return []UpdateState{
		UpdateStatePending,
		UpdateStateApproved,
		UpdateStateIgnored,
	}
}

// String implements the Stringer interface.
func (x UpdateState) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x UpdateState) IsValid() bool {
	_, err := ParseUpdateState(string(x))
	return err == nil
}

var _UpdateStateValue = map[string]UpdateState{
	"pending":  UpdateStatePending,
	"approved": UpdateStateApproved,
	"ignored":  UpdateStateIgnored,
}

// ParseUpdateState attempts to convert a string to a UpdateState.
func ParseUpdateState(name string) (UpdateState, error) {
	if x, ok := _UpdateStateValue[name]; ok {
		return x, nil
	}
	return UpdateState(""), fmt.Errorf("%s is %w", name, ErrInvalidUpdateState)
}

// MustParseUpdateState converts a string to a UpdateState, and panics if is not valid.
func MustParseUpdateState(name string) UpdateState {
	val, err := ParseUpdateState(name)
	if err != nil {
		panic(err)
	}
	return val
}

// MarshalText implements the text marshaller method.
func (x UpdateState) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *UpdateState) UnmarshalText(text []byte) error {
	tmp, err := ParseUpdateState(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

const (
	// WebhookTypeGeneric is a WebhookType of type generic.
	WebhookTypeGeneric WebhookType = "generic"
	// WebhookTypeDiun is a WebhookType of type diun.
	WebhookTypeDiun WebhookType = "diun"
)

var ErrInvalidWebhookType = fmt.Errorf("not a valid WebhookType, try [%s]", strings.Join(_WebhookTypeNames, ", "))

var _WebhookTypeNames = []string{
	string(WebhookTypeGeneric),
	string(WebhookTypeDiun),
}

// WebhookTypeNames returns a list of possible string values of WebhookType.
func WebhookTypeNames() []string {
	tmp := make([]string, len(_WebhookTypeNames))
	copy(tmp, _WebhookTypeNames)
	return tmp
}

// WebhookTypeValues returns a list of the values for WebhookType
func WebhookTypeValues() []WebhookType {
	return []WebhookType{
		WebhookTypeGeneric,
		WebhookTypeDiun,
	}
}

// String implements the Stringer interface.
func (x WebhookType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x WebhookType) IsValid() bool {
	_, err := ParseWebhookType(string(x))
	return err == nil
}

var _WebhookTypeValue = map[string]WebhookType{
	"generic": WebhookTypeGeneric,
	"diun":    WebhookTypeDiun,
}

// ParseWebhookType attempts to convert a string to a WebhookType.
func ParseWebhookType(name string) (WebhookType, error) {
	if x, ok := _WebhookTypeValue[name]; ok {
		return x, nil
	}
	return WebhookType(""), fmt.Errorf("%s is %w", name, ErrInvalidWebhookType)
}

// MustParseWebhookType converts a string to a WebhookType, and panics if is not valid.
func MustParseWebhookType(name string) WebhookType {
	val, err := ParseWebhookType(name)
	if err != nil {
		panic(err)
	}
	return val
}

// MarshalText implements the text marshaller method.
func (x WebhookType) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *WebhookType) UnmarshalText(text []byte) error {
	tmp, err := ParseWebhookType(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}
