// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package constant

import (
	"fmt"
	"strings"
)

const (
	// ActionInvocationStateCreated is a ActionInvocationState of type created.
	ActionInvocationStateCreated ActionInvocationState = "created"
	// ActionInvocationStateRunning is a ActionInvocationState of type running.
	ActionInvocationStateRunning ActionInvocationState = "running"
	// ActionInvocationStateRetrying is a ActionInvocationState of type retrying.
	ActionInvocationStateRetrying ActionInvocationState = "retrying"
	// ActionInvocationStateSuccess is a ActionInvocationState of type success.
	ActionInvocationStateSuccess ActionInvocationState = "success"
	// ActionInvocationStateError is a ActionInvocationState of type error.
	ActionInvocationStateError ActionInvocationState = "error"
)

var ErrInvalidActionInvocationState = fmt.Errorf("not a valid ActionInvocationState, try [%s]", strings.Join(_ActionInvocationStateNames, ", "))

var _ActionInvocationStateNames = []string{
	string(ActionInvocationStateCreated),
	string(ActionInvocationStateRunning),
	string(ActionInvocationStateRetrying),
	string(ActionInvocationStateSuccess),
	string(ActionInvocationStateError),
}

// ActionInvocationStateNames returns a list of possible string values of ActionInvocationState.
func ActionInvocationStateNames() []string {
	tmp := make([]string, len(_ActionInvocationStateNames))
	copy(tmp, _ActionInvocationStateNames)
	return tmp
}

// ActionInvocationStateValues returns a list of the values for ActionInvocationState
func ActionInvocationStateValues() []ActionInvocationState {
	return []ActionInvocationState{
		ActionInvocationStateCreated,
		ActionInvocationStateRunning,
		ActionInvocationStateRetrying,
		ActionInvocationStateSuccess,
		ActionInvocationStateError,
	}
}

// String implements the Stringer interface.
func (x ActionInvocationState) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ActionInvocationState) IsValid() bool {
	_, err := ParseActionInvocationState(string(x))
	return err == nil
}

var _ActionInvocationStateValue = map[string]ActionInvocationState{
	"created":  ActionInvocationStateCreated,
	"running":  ActionInvocationStateRunning,
	"retrying": ActionInvocationStateRetrying,
	"success":  ActionInvocationStateSuccess,
	"error":    ActionInvocationStateError,
}

// ParseActionInvocationState attempts to convert a string to a ActionInvocationState.
func ParseActionInvocationState(name string) (ActionInvocationState, error) {
	if x, ok := _ActionInvocationStateValue[name]; ok {
		return x, nil
	}
	return ActionInvocationState(""), fmt.Errorf("%s is %w", name, ErrInvalidActionInvocationState)
}

// MustParseActionInvocationState converts a string to a ActionInvocationState, and panics if is not valid.
func MustParseActionInvocationState(name string) ActionInvocationState {
	val, err := ParseActionInvocationState(name)
	if err != nil {
		panic(err)
	}
	return val
}

// MarshalText implements the text marshaller method.
func (x ActionInvocationState) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *ActionInvocationState) UnmarshalText(text []byte) error {
	tmp, err := ParseActionInvocationState(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

const (
	// ActionTypeShoutrrr is a ActionType of type shoutrrr.
	ActionTypeShoutrrr ActionType = "shoutrrr"
)

var ErrInvalidActionType = fmt.Errorf("not a valid ActionType, try [%s]", strings.Join(_ActionTypeNames, ", "))

var _ActionTypeNames = []string{
	string(ActionTypeShoutrrr),
}

// ActionTypeNames returns a list of possible string values of ActionType.
func ActionTypeNames() []string {
	tmp := make([]string, len(_ActionTypeNames))
	copy(tmp, _ActionTypeNames)
	return tmp
}

// ActionTypeValues returns a list of the values for ActionType
func ActionTypeValues() []ActionType {
	return []ActionType{
		ActionTypeShoutrrr,
	}
}

// String implements the Stringer interface.
func (x ActionType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ActionType) IsValid() bool {
	_, err := ParseActionType(string(x))
	return err == nil
}

var _ActionTypeValue = map[string]ActionType{
	"shoutrrr": ActionTypeShoutrrr,
}

// ParseActionType attempts to convert a string to a ActionType.
func ParseActionType(name string) (ActionType, error) {
	if x, ok := _ActionTypeValue[name]; ok {
		return x, nil
	}
	return ActionType(""), fmt.Errorf("%s is %w", name, ErrInvalidActionType)
}

// MustParseActionType converts a string to a ActionType, and panics if is not valid.
func MustParseActionType(name string) ActionType {
	val, err := ParseActionType(name)
	if err != nil {
		panic(err)
	}
	return val
}

// MarshalText implements the text marshaller method.
func (x ActionType) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *ActionType) UnmarshalText(text []byte) error {
	tmp, err := ParseActionType(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

const (
	// EventNameUpdateCreated is a EventName of type update_created.
	EventNameUpdateCreated EventName = "update_created"
	// EventNameUpdateUpdated is a EventName of type update_updated.
	EventNameUpdateUpdated EventName = "update_updated"
	// EventNameUpdateUpdatedState is a EventName of type update_updated_state.
	EventNameUpdateUpdatedState EventName = "update_updated_state"
	// EventNameUpdateUpdatedVersion is a EventName of type update_updated_version.
	EventNameUpdateUpdatedVersion EventName = "update_updated_version"
	// EventNameUpdateDeleted is a EventName of type update_deleted.
	EventNameUpdateDeleted EventName = "update_deleted"
)

var ErrInvalidEventName = fmt.Errorf("not a valid EventName, try [%s]", strings.Join(_EventNameNames, ", "))

var _EventNameNames = []string{
	string(EventNameUpdateCreated),
	string(EventNameUpdateUpdated),
	string(EventNameUpdateUpdatedState),
	string(EventNameUpdateUpdatedVersion),
	string(EventNameUpdateDeleted),
}

// EventNameNames returns a list of possible string values of EventName.
func EventNameNames() []string {
	tmp := make([]string, len(_EventNameNames))
	copy(tmp, _EventNameNames)
	return tmp
}

// EventNameValues returns a list of the values for EventName
func EventNameValues() []EventName {
	return []EventName{
		EventNameUpdateCreated,
		EventNameUpdateUpdated,
		EventNameUpdateUpdatedState,
		EventNameUpdateUpdatedVersion,
		EventNameUpdateDeleted,
	}
}

// String implements the Stringer interface.
func (x EventName) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x EventName) IsValid() bool {
	_, err := ParseEventName(string(x))
	return err == nil
}

var _EventNameValue = map[string]EventName{
	"update_created":         EventNameUpdateCreated,
	"update_updated":         EventNameUpdateUpdated,
	"update_updated_state":   EventNameUpdateUpdatedState,
	"update_updated_version": EventNameUpdateUpdatedVersion,
	"update_deleted":         EventNameUpdateDeleted,
}

// ParseEventName attempts to convert a string to a EventName.
func ParseEventName(name string) (EventName, error) {
	if x, ok := _EventNameValue[name]; ok {
		return x, nil
	}
	return EventName(""), fmt.Errorf("%s is %w", name, ErrInvalidEventName)
}

// MustParseEventName converts a string to a EventName, and panics if is not valid.
func MustParseEventName(name string) EventName {
	val, err := ParseEventName(name)
	if err != nil {
		panic(err)
	}
	return val
}

// MarshalText implements the text marshaller method.
func (x EventName) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *EventName) UnmarshalText(text []byte) error {
	tmp, err := ParseEventName(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

const (
	// EventStateCreated is a EventState of type created.
	EventStateCreated EventState = "created"
	// EventStateEnqueued is a EventState of type enqueued.
	EventStateEnqueued EventState = "enqueued"
)

var ErrInvalidEventState = fmt.Errorf("not a valid EventState, try [%s]", strings.Join(_EventStateNames, ", "))

var _EventStateNames = []string{
	string(EventStateCreated),
	string(EventStateEnqueued),
}

// EventStateNames returns a list of possible string values of EventState.
func EventStateNames() []string {
	tmp := make([]string, len(_EventStateNames))
	copy(tmp, _EventStateNames)
	return tmp
}

// EventStateValues returns a list of the values for EventState
func EventStateValues() []EventState {
	return []EventState{
		EventStateCreated,
		EventStateEnqueued,
	}
}

// String implements the Stringer interface.
func (x EventState) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x EventState) IsValid() bool {
	_, err := ParseEventState(string(x))
	return err == nil
}

var _EventStateValue = map[string]EventState{
	"created":  EventStateCreated,
	"enqueued": EventStateEnqueued,
}

// ParseEventState attempts to convert a string to a EventState.
func ParseEventState(name string) (EventState, error) {
	if x, ok := _EventStateValue[name]; ok {
		return x, nil
	}
	return EventState(""), fmt.Errorf("%s is %w", name, ErrInvalidEventState)
}

// MustParseEventState converts a string to a EventState, and panics if is not valid.
func MustParseEventState(name string) EventState {
	val, err := ParseEventState(name)
	if err != nil {
		panic(err)
	}
	return val
}

// MarshalText implements the text marshaller method.
func (x EventState) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *EventState) UnmarshalText(text []byte) error {
	tmp, err := ParseEventState(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

const (
	// FilterPresetTypeUpdate is a FilterPresetType of type update.
	FilterPresetTypeUpdate FilterPresetType = "update"
)

var ErrInvalidFilterPresetType = fmt.Errorf("not a valid FilterPresetType, try [%s]", strings.Join(_FilterPresetTypeNames, ", "))

var _FilterPresetTypeNames = []string{
	string(FilterPresetTypeUpdate),
}

// FilterPresetTypeNames returns a list of possible string values of FilterPresetType.
func FilterPresetTypeNames() []string {
	tmp := make([]string, len(_FilterPresetTypeNames))
	copy(tmp, _FilterPresetTypeNames)
	return tmp
}

// FilterPresetTypeValues returns a list of the values for FilterPresetType
func FilterPresetTypeValues() []FilterPresetType {
	return []FilterPresetType{
		FilterPresetTypeUpdate,
	}
}

// String implements the Stringer interface.
func (x FilterPresetType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x FilterPresetType) IsValid() bool {
	_, err := ParseFilterPresetType(string(x))
	return err == nil
}

var _FilterPresetTypeValue = map[string]FilterPresetType{
	"update": FilterPresetTypeUpdate,
}

// ParseFilterPresetType attempts to convert a string to a FilterPresetType.
func ParseFilterPresetType(name string) (FilterPresetType, error) {
	if x, ok := _FilterPresetTypeValue[name]; ok {
		return x, nil
	}
	return FilterPresetType(""), fmt.Errorf("%s is %w", name, ErrInvalidFilterPresetType)
}

// MustParseFilterPresetType converts a string to a FilterPresetType, and panics if is not valid.
func MustParseFilterPresetType(name string) FilterPresetType {
	val, err := ParseFilterPresetType(name)
	if err != nil {
		panic(err)
	}
	return val
}

// MarshalText implements the text marshaller method.
func (x FilterPresetType) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *FilterPresetType) UnmarshalText(text []byte) error {
	tmp, err := ParseFilterPresetType(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

const (
	// UpdateStatePending is a UpdateState of type pending.
	UpdateStatePending UpdateState = "pending"
	// UpdateStateApproved is a UpdateState of type approved.
	UpdateStateApproved UpdateState = "approved"
	// UpdateStateIgnored is a UpdateState of type ignored.
	UpdateStateIgnored UpdateState = "ignored"
)

var ErrInvalidUpdateState = fmt.Errorf("not a valid UpdateState, try [%s]", strings.Join(_UpdateStateNames, ", "))

var _UpdateStateNames = []string{
	string(UpdateStatePending),
	string(UpdateStateApproved),
	string(UpdateStateIgnored),
}

// UpdateStateNames returns a list of possible string values of UpdateState.
func UpdateStateNames() []string {
	tmp := make([]string, len(_UpdateStateNames))
	copy(tmp, _UpdateStateNames)
	return tmp
}

// UpdateStateValues returns a list of the values for UpdateState
func UpdateStateValues() []UpdateState {
	return []UpdateState{
		UpdateStatePending,
		UpdateStateApproved,
		UpdateStateIgnored,
	}
}

// String implements the Stringer interface.
func (x UpdateState) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x UpdateState) IsValid() bool {
	_, err := ParseUpdateState(string(x))
	return err == nil
}

var _UpdateStateValue = map[string]UpdateState{
	"pending":  UpdateStatePending,
	"approved": UpdateStateApproved,
	"ignored":  UpdateStateIgnored,
}

// ParseUpdateState attempts to convert a string to a UpdateState.
func ParseUpdateState(name string) (UpdateState, error) {
	if x, ok := _UpdateStateValue[name]; ok {
		return x, nil
	}
	return UpdateState(""), fmt.Errorf("%s is %w", name, ErrInvalidUpdateState)
}

// MustParseUpdateState converts a string to a UpdateState, and panics if is not valid.
func MustParseUpdateState(name string) UpdateState {
	val, err := ParseUpdateState(name)
	if err != nil {
		panic(err)
	}
	return val
}

// MarshalText implements the text marshaller method.
func (x UpdateState) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *UpdateState) UnmarshalText(text []byte) error {
	tmp, err := ParseUpdateState(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

const (
	// WebhookTypeGeneric is a WebhookType of type generic.
	WebhookTypeGeneric WebhookType = "generic"
	// WebhookTypeDiun is a WebhookType of type diun.
	WebhookTypeDiun WebhookType = "diun"
)

var ErrInvalidWebhookType = fmt.Errorf("not a valid WebhookType, try [%s]", strings.Join(_WebhookTypeNames, ", "))

var _WebhookTypeNames = []string{
	string(WebhookTypeGeneric),
	string(WebhookTypeDiun),
}

// WebhookTypeNames returns a list of possible string values of WebhookType.
func WebhookTypeNames() []string {
	tmp := make([]string, len(_WebhookTypeNames))
	copy(tmp, _WebhookTypeNames)
	return tmp
}

// WebhookTypeValues returns a list of the values for WebhookType
func WebhookTypeValues() []WebhookType {
	return []WebhookType{
		WebhookTypeGeneric,
		WebhookTypeDiun,
	}
}

// String implements the Stringer interface.
func (x WebhookType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x WebhookType) IsValid() bool {
	_, err := ParseWebhookType(string(x))
	return err == nil
}

var _WebhookTypeValue = map[string]WebhookType{
	"generic": WebhookTypeGeneric,
	"diun":    WebhookTypeDiun,
}

// ParseWebhookType attempts to convert a string to a WebhookType.
func ParseWebhookType(name string) (WebhookType, error) {
	if x, ok := _WebhookTypeValue[name]; ok {
		return x, nil
	}
	return WebhookType(""), fmt.Errorf("%s is %w", name, ErrInvalidWebhookType)
}

// MustParseWebhookType converts a string to a WebhookType, and panics if is not valid.
func MustParseWebhookType(name string) WebhookType {
	val, err := ParseWebhookType(name)
	if err != nil {
		panic(err)
	}
	return val
}

// MarshalText implements the text marshaller method.
func (x WebhookType) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *WebhookType) UnmarshalText(text []byte) error {
	tmp, err := ParseWebhookType(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}
